name: Java CI

on: 
  push:
  schedule:
   - cron:  '*/2 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: raipc/checkout@v1
    - name: Set up JDK 1.8
      uses: raipc/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
